# https://taskfile.dev

version: '3'
silent: true

includes:
  docker: ./taskfiles/Docker.yml
  op: ./taskfiles/Operations.yml
  py: ./taskfiles/Python.yml

tasks:
  default:
    desc: "List all tasks."
    cmds:
      - task --list-all
